#!/usr/bin/env python3
"""
convert_assets.py - PNG -> LVGL C array generator  [SPEC section 8]

Reads assets/manifest.json, converts each RGBA8888 PNG in assets/src/ to a
C array in src/assets/, and rewrites the declaration block in include/assets.h.

PHASE 2: the manifest is empty on purpose. See include/assets.h. This script
exists now so that regenerating assets is one reviewable command from the
moment the first PNG lands, rather than a hand-rolled step invented later
under time pressure.

Design rules this enforces, all from section 8:
  - PNGs are authored at FINAL pixel size; this script never rescales.
  - Output is LV_IMG_CF_TRUE_COLOR_ALPHA.
  - RGB565 byte order must match lv_conf.h's LV_COLOR_16_SWAP=0.

Usage:  python3 tools/convert_assets.py [--check]
        --check verifies generated files are up to date without writing.

Requires Pillow. It is NOT currently installed on this machine, which is one
more reason Phase 2 ships no art: install it when the first real asset exists.
    pip install Pillow
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "manifest.json")
SRC_DIR = os.path.join(ROOT, "assets", "src")
OUT_DIR = os.path.join(ROOT, "src", "assets")
HEADER = os.path.join(ROOT, "include", "assets.h")

MARKER = "/* No assets yet."


def rgb565(r, g, b):
    """Pack to RGB565 little-endian, matching LV_COLOR_16_SWAP=0."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(name, png_path):
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Pillow is required to convert assets: pip install Pillow")

    img = Image.open(png_path).convert("RGBA")
    w, h = img.size
    px = img.load()

    body = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            c = rgb565(r, g, b)
            body.append("0x%02X,0x%02X,0x%02X," % (c & 0xFF, (c >> 8) & 0xFF, a))

    lines = [
        '#include "lvgl.h"',
        "",
        "/* GENERATED by tools/convert_assets.py - do not edit by hand. */",
        "",
        "static const uint8_t %s_map[] = {" % name,
    ]
    for i in range(0, len(body), 12):
        lines.append("    " + "".join(body[i:i + 12]))
    lines += [
        "};",
        "",
        "const lv_img_dsc_t %s = {" % name,
        "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        "    .header.w = %d," % w,
        "    .header.h = %d," % h,
        "    .data_size = %d," % (w * h * 3),
        "    .data = %s_map," % name,
        "};",
        "",
    ]
    return "\n".join(lines), w, h


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify without writing")
    args = ap.parse_args()

    with open(MANIFEST) as f:
        manifest = json.load(f)

    assets = manifest.get("assets", [])
    if not assets:
        print("manifest is empty - nothing to convert (expected in Phase 2)")
        return 0

    os.makedirs(OUT_DIR, exist_ok=True)
    decls, stale = [], []

    for a in assets:
        name = a["name"]
        png = os.path.join(SRC_DIR, a["src"])
        if not os.path.exists(png):
            sys.exit("missing source PNG: %s" % png)
        text, w, h = convert(name, png)
        out = os.path.join(OUT_DIR, "img_%s.c" % name)
        old = open(out).read() if os.path.exists(out) else None
        if old != text:
            stale.append(out)
            if not args.check:
                with open(out, "w") as f:
                    f.write(text)
        decls.append("LV_IMG_DECLARE(%s);   /* %dx%d */" % (name, w, h))
        print("  %-20s %3dx%-3d -> %s" % (name, w, h, os.path.basename(out)))

    hdr = open(HEADER).read()
    i = hdr.find(MARKER)
    if i < 0:
        sys.exit("marker not found in include/assets.h")
    j = hdr.find("*/", i)
    block = "/* Generated declarations - do not edit by hand. */\n" + "\n".join(decls)
    new_hdr = hdr[:i] + block + hdr[j + 2:]
    if new_hdr != hdr:
        stale.append(HEADER)
        if not args.check:
            with open(HEADER, "w") as f:
                f.write(new_hdr)

    if args.check and stale:
        print("STALE (run without --check):")
        for s in stale:
            print("  " + s)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
